server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-18-232-216-229.compute-1.amazonaws.com:5432/d3456bda0053gc
    username: tgbyszlmbikgym
    password: 5237792dd3b631c6ecb04f114819904ab4669c596a3d2aca65ebaf4989cd809b
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
